"""Load config/promo_sources.yaml - the hand-maintained brand list for the
"Promo Uebersicht" vertical.

Deliberately separate from config.py/watchlist.yaml: those describe operator
PRESS sources (auto-generated by scripts/build_sources.py). This file
describes consumer promo/Aktionen pages - a different content type, crawled
by a different collector (see collect/promo_snapshot.py) - so keeping the
loader separate avoids entangling the two schemas.

**Eine Marke, MEHRERE Seiten** (08.08.2026). Bis dahin hatte jede Marke genau
eine URL, und das war die eigentliche Luecke der Rubrik: eine Aktionsseite
zeigt nie alle laufenden Aktionen eines Anbieters. Die Geraeteaktion steht
unter /handys, die Wechselpraemie unter /wechseln, die Tarifaktion unter
/tarife, die befristete Kampagne auf einer eigenen Landingpage - und die
Uebersichtsseite, die bisher als einzige Quelle konfiguriert war, verlinkt
sie hoechstens. Antonio: "dass man wirklich alle Promo-Aktionen von den
einzelnen Unternehmen auf dem Schirm hat, dafuer braucht es wahrscheinlich
mehr als eine Quelle pro Unternehmen."

Deshalb traegt jede Marke jetzt eine LISTE von Seiten. Das Feld `url` bleibt
die Leitseite (sie steht auf der Uebersicht als Markenlink und ist der
Rueckfall fuer ein Angebot ohne eigenen Tiefenlink); `pages:` nennt die
weiteren. Eine Marke ohne `pages:` verhaelt sich exakt wie vorher - alle
bestehenden Eintraege bleiben gueltig, ohne dass eine Zeile geaendert werden
muss.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import yaml

# Etikett der Leitseite, wenn die YAML keins nennt. Steht so auf der
# Quellen-Unterseite - "Uebersicht" beschreibt, was sie ist: die Seite, die
# der Anbieter selbst als Einstieg in seine Aktionen fuehrt.
_LEITSEITE_LABEL = "Übersicht"


@dataclass
class PromoPage:
    """Eine einzelne abgefragte Seite einer Marke.

    `label` ist reine Anzeige (Quellen-Unterseite) und darf leer sein.
    `kind` ist pro SEITE frei waehlbar, nicht pro Marke: bei congstar ist die
    Angebotsuebersicht statisch abrufbar, die Kampagnen-Landingpage aber
    JS-gerendert - eine Marke kann also beides gleichzeitig brauchen.
    """
    url: str
    kind: str = "static"          # static | js | skip
    label: str = ""
    note: str = ""

    @property
    def crawlable(self) -> bool:
        return self.kind in ("static", "js")


@dataclass
class PromoSource:
    name: str
    url: str
    tier: int = 2
    kind: str = "static"          # static | js | skip  (Art der LEITSEITE)
    group: str = ""               # Mutter-/Markenfamilie, sofern bekannt
    internal_reference: bool = False
    note: str = ""
    # Achse C des Wichtigkeits-Scores (analyze/promo_ranker.py): Marktreich-
    # weite der Marke, 1-3. Bewusst ein eigenes Feld statt einer Ableitung
    # aus dem Tier - eine Handelsmarke wie ALDI TALK erreicht deutlich mehr
    # Menschen als eine reine Online-Zweitmarke, obwohl beide Tier 2 sind.
    # Fehlt das Feld, faellt promo_ranker.reach_axis() auf das Tier zurueck.
    reach: int | None = None
    # Platz in der Anbieter-Rangfolge (1 = wichtigster). Antonio am
    # 08.08.2026: "die groessten Anbieter wie Telekom etc. an erster Stelle,
    # soll also nach Wichtigkeit der Anbieter geordnet werden." Bis dahin
    # sortierte die Uebersicht die Marken nach dem Score ihrer staerksten
    # Aktion - eine Rangliste der ANGEBOTE, keine des Marktes: Otelo stand
    # oben und die Telekom auf Platz zehn, weil ihre JS-Seiten in dem Lauf
    # nur zwei Angebote hergaben.
    #
    # Bewusst ein gepflegtes Feld und keine Rechnung: Marktgewicht steht in
    # keiner Zahl dieses Projekts. Fehlt es, wird aus tier und reach ein
    # Rang abgeleitet (siehe report/promo.RANG_UNGESETZT), die Marke faellt
    # dann hinter jede gepflegte.
    rang: int | None = None
    # Die WEITEREN Seiten dieser Marke (YAML: `pages:`). Die Leitseite steht
    # NICHT hier drin - sie kommt aus url/kind und wird von `pages` unten
    # vorangestellt. Getrennt gehalten, damit ein Bestandseintrag ohne
    # `pages:` unveraendert weiterlaeuft und `url` weiterhin eindeutig "die
    # Seite, auf die die Marke verlinkt wird" bedeutet.
    extra_pages: list[PromoPage] = field(default_factory=list)

    @property
    def pages(self) -> list[PromoPage]:
        """Alle Seiten dieser Marke, Leitseite zuerst."""
        return [PromoPage(url=self.url, kind=self.kind,
                          label=_LEITSEITE_LABEL, note=self.note)] + list(self.extra_pages)

    @property
    def crawled_pages(self) -> list[PromoPage]:
        return [p for p in self.pages if p.crawlable]

    @property
    def crawlable(self) -> bool:
        """Wird diese Marke ueberhaupt abgefragt?

        Ja, sobald IRGENDEINE ihrer Seiten crawlbar ist. Eine Marke, deren
        Leitseite ein dokumentierter Sonderfall (`kind: skip`) ist, deren
        Kampagnenseite sich aber abrufen laesst, wird beobachtet - sie darf
        auf der Uebersicht nicht als ungeprueft durchfallen.
        """
        return any(p.crawlable for p in self.pages)


@dataclass
class PromoConfig:
    sources: list[PromoSource] = field(default_factory=list)

    @property
    def crawled_sources(self) -> list[PromoSource]:
        return [s for s in self.sources if s.crawlable]

    @property
    def competitor_sources(self) -> list[PromoSource]:
        return [s for s in self.sources if not s.internal_reference]

    @property
    def page_count(self) -> int:
        """Zahl der tatsaechlich abgefragten SEITEN - die Kennzahl, die den
        Ausbau dieser Rubrik misst. Die Zahl der Marken sagt darueber nichts
        mehr aus, seit eine Marke mehrere Seiten haben kann (gleiche Lehre
        wie bei scripts/quellen_zaehlen.py: gezaehlt wird, was ein Lauf
        wirklich abfragt, nicht was in der YAML steht)."""
        return sum(len(s.crawled_pages) for s in self.sources)


def _parse_pages(raw_pages, brand_url: str) -> list[PromoPage]:
    """`pages:`-Block einer Marke lesen. Eine Seite, die (nach Normalisierung
    von Schraegstrich und Schema) dieselbe wie die Leitseite ist, faellt
    raus - sonst wuerde sie doppelt abgefragt und die LLM-Extraktion liefe
    zweimal ueber denselben Text."""
    seen = {_normalize_url(brand_url)}
    out: list[PromoPage] = []
    for p in raw_pages or []:
        if not isinstance(p, dict):
            continue
        url = str(p.get("url") or "").strip()
        if not url:
            continue
        key = _normalize_url(url)
        if key in seen:
            continue
        seen.add(key)
        out.append(PromoPage(
            url=url, kind=str(p.get("kind") or "static"),
            label=str(p.get("label") or ""), note=str(p.get("note") or "")))
    return out


def _normalize_url(url: str) -> str:
    """Vergleichsform einer URL: ohne Schema, ohne fuehrendes www., ohne
    abschliessenden Schraegstrich, klein. Nur fuer Gleichheitsvergleiche -
    abgefragt wird immer die URL, wie sie in der YAML steht."""
    u = (url or "").strip().lower()
    for prefix in ("https://", "http://"):
        if u.startswith(prefix):
            u = u[len(prefix):]
            break
    if u.startswith("www."):
        u = u[4:]
    return u.rstrip("/")


def load_promo_config(root: Path) -> PromoConfig:
    """Read config/promo_sources.yaml below *root*. Missing file -> empty
    config (the promo stage then simply does nothing, failsafe by design)."""
    path = Path(root) / "config" / "promo_sources.yaml"
    if not path.exists():
        return PromoConfig(sources=[])
    with open(path, "r", encoding="utf-8") as fh:
        raw = yaml.safe_load(fh) or {}
    sources = [
        PromoSource(
            name=b["name"], url=b["url"], tier=int(b.get("tier", 2)),
            kind=b.get("kind", "static"), group=b.get("group", ""),
            internal_reference=bool(b.get("internal_reference", False)),
            note=b.get("note", ""),
            reach=int(b["reach"]) if str(b.get("reach", "")).strip().isdigit() else None,
            rang=int(b["rang"]) if str(b.get("rang", "")).strip().isdigit() else None,
            extra_pages=_parse_pages(b.get("pages"), b["url"]),
        )
        for b in (raw.get("brands") or []) if b.get("name") and b.get("url")
    ]
    return PromoConfig(sources=sources)
