"""Load config/promo_sources.yaml - the hand-maintained brand list for the
"Promo Uebersicht" vertical.

Deliberately separate from config.py/watchlist.yaml: those describe operator
PRESS sources (auto-generated by scripts/build_sources.py). This file
describes consumer promo/Aktionen pages - a different content type, crawled
by a different collector (see collect/promo_snapshot.py) - so keeping the
loader separate avoids entangling the two schemas.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import yaml


@dataclass
class PromoSource:
    name: str
    url: str
    tier: int = 2
    kind: str = "static"          # static | js | skip
    group: str = ""               # Mutter-/Markenfamilie, sofern bekannt
    internal_reference: bool = False
    note: str = ""
    # Achse C des Wichtigkeits-Scores (analyze/promo_ranker.py): Marktreich-
    # weite der Marke, 1-3. Bewusst ein eigenes Feld statt einer Ableitung
    # aus dem Tier - eine Handelsmarke wie ALDI TALK erreicht deutlich mehr
    # Menschen als eine reine Online-Zweitmarke, obwohl beide Tier 2 sind.
    # Fehlt das Feld, faellt promo_ranker.reach_axis() auf das Tier zurueck.
    reach: int | None = None

    @property
    def crawlable(self) -> bool:
        return self.kind in ("static", "js")


@dataclass
class PromoConfig:
    sources: list[PromoSource] = field(default_factory=list)

    @property
    def crawled_sources(self) -> list[PromoSource]:
        return [s for s in self.sources if s.crawlable]

    @property
    def competitor_sources(self) -> list[PromoSource]:
        return [s for s in self.sources if not s.internal_reference]


def load_promo_config(root: Path) -> PromoConfig:
    """Read config/promo_sources.yaml below *root*. Missing file -> empty
    config (the promo stage then simply does nothing, failsafe by design)."""
    path = Path(root) / "config" / "promo_sources.yaml"
    if not path.exists():
        return PromoConfig(sources=[])
    with open(path, "r", encoding="utf-8") as fh:
        raw = yaml.safe_load(fh) or {}
    sources = [
        PromoSource(
            name=b["name"], url=b["url"], tier=int(b.get("tier", 2)),
            kind=b.get("kind", "static"), group=b.get("group", ""),
            internal_reference=bool(b.get("internal_reference", False)),
            note=b.get("note", ""),
            reach=int(b["reach"]) if str(b.get("reach", "")).strip().isdigit() else None,
        )
        for b in (raw.get("brands") or []) if b.get("name") and b.get("url")
    ]
    return PromoConfig(sources=sources)
